### ISSUE TITLE
Change Json HPP dependency to package-based 

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1084]
This works then Deb9 based and related systems as the package is there.

For red hat / yum based systems, there needs to be another solution.

**Comment by GMishx** [comment]
### There are two solutions,
1.  Take the library approach
2.  Commit the json.hpp

*  With the first approach, there is a library called `libjsoncpp-dev` which is available in Debian based distros but not available in Red Hat based distros. But there is another library called `libjson-c` which is available in both Debian and Red Hat based distros. The only problem with `libjson-c` is that the library is written in C and the copyright agent is in C++. Otherwise, `libjson-c` will be a perfect replacement.
*  The idea of committing the json.hpp in FOSSology code-base is a simpler and cleaner approach but requires constant monitoring and syncing with the https://github.com/nlohmann/json.

**Comment by GMishx** [comment]
Can we go ahead with any of the solutions suggested above?

**Comment by mcjaeger** [comment]
it is working, but requires merging:
https://github.com/fossology/fossology/pull/1226
