### ISSUE TITLE
Create a job in maintenance agent to clean inactive tokens from DB.

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1303]
### Description

Create a job in maintenance agent to clean inactive tokens from DB. As with current implementation, the expired tokens are kept in the DB and not deleted for audit purpose. This may result in quick build-up of huge amount of data in DB and may not be required for every instance.

One way to solve this is to create a new job in maintenance agent to clean such inactive tokens from DB which are expired **X** days ago.

#### How to reproduce

1. Install changes from #1290
1. Create some tokens.
1. Revoke tokens from UI.
1. Data remains in DB.

**Comment by Aman-Codes** [comment]
Hello @GMishx, I would like to work on this issue. 
Just wanted to clarify that do we need delete all personal_access_tokens WHERE active = 'f' OR expire_on < today
Or we want an option to specify the value of X (delete tokens expired X days ago)

**Comment by GMishx** [comment]
With the audit perspective, it is nice to keep the tokens for a predefined set of duration. So the "expire X days ago" sound a nice solution.

**Comment by Aman-Codes** [comment]
@GMishx  What would be the right place to save that value?
1. In sysconfig table in database so that it's value can be edited from the Admin>Customize page.
But that may also require to create a dbmigrate script to add the new row in earlier versions of fossology.

2. In UI provide an input box to enter the value each time the maintagent job is scheduled.
In CLI provide the value as additional command line argument.

3. In fossology.conf file.

**Comment by GMishx** [comment]
IMO, it should be put into the sysconfig table for easy access (you do not need migration script for this table).
Then the agent should accept it as a CLI parameter which will be fed by the UI reading from sysconfig table. So, if someone wants to run the agent from CLI, they can pass their own value without touching sysconfig.

What do you say?

**Comment by Aman-Codes** [comment]
Yes that sounds good. Will add it in sysconfig table.
