### ISSUE TITLE
Current master: nomos crashes on files

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1337]
### Description

Nomos crashes when scanning the SPDX license list test data. See pull request https://github.com/fossology/fossology/pull/1310

Maybe it is because a variable overruns when nomos identifies too many licenses in one file.

#### How to reproduce

take current master and scan by nomos this:

https://github.com/spdx/license-list-data

(download zip from GIthub) 

#### Screenshots

see here: https://github.com/fossology/fossology/pull/1310

### Versions

* Last commit id on master: 7088721f02ec909f6bbdd8348bc7d3354328ed2b
* also on branch: of that PR commit 45e65419e11f229cd21985c256aa7f9959a52e30
* Operating System (lsb_release -a): Vagrant u1604

### Logs

for a screenshot of the agent log (from geeky scan details), see here: https://github.com/fossology/fossology/pull/1310

**Comment by rlintu** [comment]
I did some quick study to to get an idea which would introduce this.
* 3.3.0 - no crash
* 3.4.0 - crash

So the latest PR is not the root cause for this. The main differences between 3.3.0 and 3.4.0 are
* SPDXREF()
* EXCEPTIONS()

I'll do some testing later related to those and also tune buffer sizes.

**Comment by mcjaeger** [comment]
@rlintu it feels a little bit awkward to create a PR based on your work, are planning to create a fix for this? (assuming the buffer size increase is technically OK)
