### ISSUE TITLE
Is ninka agent removed in 3.5.0 release ?

### ISSUE THREAD

**Issue by DineshDevarajan** [fossology/fossology#1355]
### Description

Ninka agent missing

#### How to reproduce

In Upload screen ninka agent is missing 

### Versions
3.5.0

**Comment by mcjaeger** [comment]
hi @DineshDevarajan, thanks for your feedback. Actually, it is not really out, but you need to install it separately.

It has been for a long time now since we have heard that some uses ninka. We felt maintaining an agent that no one uses. Also the agent is not maintained anymore, most notably w.r.t the SPDX license list, which makes considering ninka results for SPDX file output for example difficult.

Furthermore the atarashi project shall be integrated soon, which has a number of advantages too.

Maybe you could help please and let us know why you think ninka should be supported in future?

**Comment by DineshDevarajan** [comment]
Hi @mcjaeger I just wanted to know/clarify the reason why Ninka was removed.

**Comment by mcjaeger** [comment]
@DineshDevarajan so, would you be Ok to close it?

**Comment by DineshDevarajan** [comment]
yes Please and thanks for the update.
