### ISSUE TITLE
What do you do with abandoned temprorary files?

### ISSUE THREAD

**Issue by W-Park** [fossology/fossology#1399]
### Description

I suppose fossology stores temprorary files on /repository/HOSTNAME/ununpack and /repository/HOSTNAME/wget 
Now I got numbers of abandoned directories under it and it uses a lot of my disk
(some of them use like hundreds of GB)

And I'd like ask two things;
1. What does others do with those temprorary files?
 - if it could be useful for some reason, I'd like to keep it. If not, I don't want to waste my storage.
2. Is there anyway I can find where did the temprorary directories come from? (from which upload?)

#### Screenshots

![image](https://user-images.githubusercontent.com/33045921/61024776-a60ba800-a3e9-11e9-8421-ccd8a37fb2a4.png)
![image](https://user-images.githubusercontent.com/33045921/61024798-b0c63d00-a3e9-11e9-8331-772b986b0441.png)

### Versions

* Last commit id on master:#171d4d(3.5.0)
* Operating System (lsb_release -a):

**Comment by GMishx** [comment]
Hello @W-Park,

These files are actually created by `wget_agent` and `ununpack` agent for processing. Once the processing is done successfully, these files are moved to /repository/HOSTNAME/files and /repository/HOSTNAME/gold.

But if due to some reason, the agents crash in between the process they are left out in these temporary locations.

So, you can safely delete them but there is no direct way to tell these files comes from which upload. You can always inspect them manually to figure out something useful.

**Comment by W-Park** [comment]
Hi @GMishx,
Thank you for reply.
I just was wondering if the temporary files can do any good.
Now I don't see any reason to remove them.
Thank you for helping me decide. :)
