### ISSUE TITLE
Change DB encoding from SQL_ASCII to UTF8

### ISSUE THREAD

**Issue by alpianon** [fossology/fossology#1492]
### Description

I was in need to export some data (copyright notices) from Fossology DB to another application and I ran into the problem of character encoding. Fossology DB uses SQL_ASCII, which is pure evil when you have to export data somewhere else (or when you want to use tools like phppgadmin).

In the end I decided to convert the Fossology DB into UTF8, with the help of [this blog post](https://www.endpoint.com/blog/2017/07/21/postgres-migrating-sqlascii-to-utf-8). After that, I ran a lot of copyright and license scans on that machine, and I got no errors whatsoever due to character encoding problems. So it seems that no Fossology component actually depends on or requires SQL_ASCII (or that I have been lucky so far...).

**Use of SQL_ASCII encoding in Fossology DB is probably due to legacy reasons, but it should be time to switch to UTF8 encoding**. Dan Stangel said that in a [comment](https://github.com/fossology/fossology/blob/828d8d523edff3264e27e0eab00f3e71ed654247/src/testing/db/create_test_database.php#L286) within Fossology code about 7 years ago...

Probably the only issue would be for updates from previous installations, but in that case the old SQL_ASCII encoding may be kept.

What do you think?

**Comment by GMishx** [comment]
Hello @alpianon,

I do changed the FOSSology DB encoding to UTF-8 (following [this blog post](http://blog.e-shell.org/134) on my development machine but now I am running into problems.

If you try to scan some binary files, I am trying with [NuGet.Client](https://github.com/NuGet/NuGet.Client) in particular some test dlls like https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/Packages/InstallPackageRespectReferencesAccordingToDifferentFrameworks/files/RefPackage.1.0.0/lib/sl40/fear.dll, which contains text like `Copyright ©`. These texts are picked up by Copyright agent.

Now, since this file is binary and not text file, the data captured by the agent also contains some binary information. And if agent tries to insert it into UTF-8 DB, this binary string can not be stored as a `Text` in `copyright.content` column as it is not a valid UTF-8 text. Which results in data loss.

If you check the [character set support documentation](https://www.postgresql.org/docs/9.3/multibyte.html), it says:
> When the server character set is SQL_ASCII, the server interprets byte values 0-127 according to the ASCII standard, while byte values 128-255 are taken as uninterpreted characters.

Which means, it can hold the binary data captured by the agent along with valid texts without any issues, but you will face problems while exporting this data somewhere else (as you've mentioned).

I tried various methods to covert this data to UTF-8 in copyright agent itself but unable do it as the binary data does not have any valid text encoding and thus can not be converted to UTF-8 in a straight forward way.

If this conversion can be done somehow, we can make the default encoding of FOSSology DB to UTF-8.

**Comment by alpianon** [comment]
I usually do not scan binary files but only source files through Fossology, so that is probably why I did not encounter any issue.

> Which means, it can hold the binary data captured by the agent along with valid texts without any issues, but you will face problems while exporting this data somewhere else (as you've mentioned).
> I tried various methods to covert this data to UTF-8 in copyright agent itself but unable do it as the binary data does not have any valid text encoding and thus can not be converted to UTF-8 in a straight forward way.

Very likely such data have no meaning at all, or even if they have a meaning, one would have to try to "decode" them on a case by case basis (not worth it in most cases), so there is little use in collecting them. Maybe the copyright agent, when scanning a binary file, should only search for ASCII or UTF8 valid characters, and ignore the rest. 

What do you think?

**Comment by alpianon** [comment]
> Maybe the copyright agent, when scanning a binary file, should only search for ASCII or UTF8 valid characters, and ignore the rest.

And maybe this could be made optional (so non-UTF8 characters are ignored only when you choose to use an UTF8 encoded DB)

**Comment by GMishx** [comment]
> > Maybe the copyright agent, when scanning a binary file, should only search for ASCII or UTF8 valid characters, and ignore the rest.
> 
> And maybe this could be made optional (so non-UTF8 characters are ignored only when you choose to use an UTF8 encoded DB)

The binary data actually make no sense. Even symbols in other languages fall under UTF-8 encoding. We need to find a way to eliminate whatever is not UTF-8 encodable. It will solve every problem.
