### ISSUE TITLE
Several dependencies are missing in fo-installdeps 

### ISSUE THREAD

**Issue by sjha2048** [fossology/fossology#1631]
### Description

While installing fossology from the source It came into my sight that there are several missing dependencies which can be added into fo-installdeps so that the installation process will be more smooth.
these dependencies can be added:
libpq-dev
libjsoncpp-dev
libboost-all-dev
libssl-dev
libjson-c-dev

### Versions

* Operating System (lsb_release -a): Pop!_OS 19.10

**Comment by GMishx** [comment]
Hello @sjha2048, the dependencies are also distributed per agent basis under `src/<agent>/mod_deps` files. You had a look there?

**Comment by sjha2048** [comment]
sure I'll have a look

**Comment by GMishx** [comment]
Did you get a chance to check the dependencies @sjha2048 ?

**Comment by sjha2048** [comment]
sorry for the late reply, I was only able to find two of these packages in mod_deps files
* libjsoncpp-dev
* libjson-c-dev
the rest are missing

**Comment by GMishx** [comment]
Hello @sjha2048

Here are the locations of each dependency:

* libpq-dev : Will be installed by postgres package but should be listed in dependency list.
* libjsoncpp-dev : https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/copyright/mod_deps#L80
* libboost-all-dev : (note, only required packages are installed instead of `all`) https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/copyright/mod_deps#L80
* libssl-dev : (will be removed by #1545) https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/delagent/mod_deps#L79
* libjson-c-dev : https://github.com/fossology/fossology/blob/b5a389be8ef413fc488b56700ea23bdf3ff9c73a/src/nomos/mod_deps#L80

**Comment by sjha2048** [comment]
shall I add libpq-dev then?

**Comment by GMishx** [comment]
Sure, please go ahead
