### ISSUE TITLE
Rest end point {{baseUrl}}/jobs?upload=16 providing wrong information 

### ISSUE THREAD

**Issue by SrikanthShyamanur** [fossology/fossology#1800]
### Description

Rest end point {{baseUrl}}/jobs?upload=16 providing wrong information 

#### How to reproduce

- Upload a vcs / file 
- perform can 
- perform delete of upload 
when the upload is in process 
- Query for job status  {{baseUrl}}/jobs?upload=16 

It should provide proper information of each step, but it will override the status of each step with the latest step status.Check the JSON below 

#### Screenshots

```
[
    {
        "id": 18,
        "name": "wget",
        "queueDate": "2020-06-26 19:28:16.535386+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 19,
        "name": "WLS",
        "queueDate": "2020-06-29 04:18:01.752964+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 128,
        "name": "WLS",
        "queueDate": "2020-07-31 11:07:51.292989+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Processing"
    },
    {
        "id": 137,
        "name": "Delete",
        "queueDate": "2020-09-11 08:10:16.075719+00",
        "uploadId": "16",
        "userId": "3",
        "groupId": "3",
        "eta": 2275,
        "status": "Processing"
    }
]
```

### Versions

* FOSSology version 3.8.0-52-gd9f6f6753 (code revision d9f6f6)

**Comment by SrikanthShyamanur** [comment]
More example:

Below its not clear which step has failed, but it is reflecting for all. 

```
[
    {
        "id": 108,
        "name": "wget",
        "queueDate": "2020-08-20 14:29:38.954328+00",
        "uploadId": "56",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    },
    {
        "id": 118,
        "name": "LMAX-Exchange_disruptor",
        "queueDate": "2020-08-20 14:54:53.185116+00",
        "uploadId": "56",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    },
    {
        "id": 363,
        "name": "Delete",
        "queueDate": "2020-08-25 15:40:51.076099+00",
        "uploadId": "56",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    }
]
```

**Comment by DineshDevarajan** [comment]
@GMishx 
RCA:
Below issue happens when upload id is passed in /jobs endpoint  (http://localhost/repo/api/v1/jobs?upload=id)

getFilteredResults -> updateEtaAndStatus :

1. getFilteredResults  :  All the job's of the upload is taken and updateEtaAndStatus is called with each job object
2. But in updateEtaAndStatus function while getting the jobqueue value using getAllJobStatus() always upload id is passed and using upload id all the job status are taken ( say for example : ununpack, nomos and delagent) . if one of the job fails all are considered failed due to this. 

https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/JobController.php#L212

Shall we implement a function in JobDao.php to get the jobqueue details based on the  job id using below query.

`SELECT jobqueue.jq_pk as jq_pk,
              jobqueue.jq_end_bits as end_bits
       FROM jobqueue
         INNER JOIN job
           ON jobqueue.jq_job_fk = job.job_pk
         LEFT JOIN group_user_member gm
           ON gm.user_fk = job_user_fk
       WHERE jobqueue.jq_job_fk = <id>  ;`

**Comment by DineshDevarajan** [comment]
@GMishx I tried to implement a function in JobDao.php to get the jq_job_fk or job id as input and return the jq_pk and jq_end_bits. After which i was able to successfully get the status as below. Please let me know if the approach is fine so i will create a PR to fix #1800

[
    {
        "id": 8,
        "name": "atarashi-master.zip",
        "queueDate": "2020-10-16 06:43:21.956237+00",
        "uploadId": "8",
        "userId": "3",
        "groupId": "4",
        "eta": 0,
        **"status": "Completed"**
    },
    {
        "id": 9,
        "name": "atarashi-master.zip",
        "queueDate": "2020-10-16 06:51:00.706768+00",
        "uploadId": "8",
        "userId": "3",
        "groupId": "4",
        "eta": 0,
        **"status": "Failed"**
    },
    {
        "id": 10,
        "name": "Delete",
        "queueDate": "2020-10-16 06:54:37.544471+00",
        "uploadId": "8",
        "userId": "3",
        "groupId": "4",
        "eta": 0,
        **"status": "Completed"**
    }
]

**Comment by SrikanthShyamanur** [comment]
In the above test result , both has same name **atarashi-master.zip** , one is **completed** and other is **Failed** - its confusing / or I am reading it wrong ? or is it an another issue ?

{
"id": 8,
**"name": "atarashi-master.zip",**
"queueDate": "2020-10-16 06:43:21.956237+00",
"uploadId": "8",
"userId": "3",
"groupId": "4",
"eta": 0,
"status": "Completed"
},
{
"id": 9,
**"name": "atarashi-master.zip",**
"queueDate": "2020-10-16 06:51:00.706768+00",
"uploadId": "8",
"userId": "3",
"groupId": "4",
"eta": 0,
"status": "Failed"
},

**Comment by DineshDevarajan** [comment]
@SrikanthShyamanur I was trying with the upload from file which is why id =8 and id =9 are with same files. 
id = 8  is for unpacking the atarashi-master.zip and id=9 is for nomos and id=10 is for deleting the same.

When we use upload from VCS we will the name of job as wget. correct me if i am wrong @GMishx

**Comment by GMishx** [comment]
Actually the `/jobs` endpoint is simplified and needs to be enhanced. So right now, if you upload and package, start a scan and schedule nomos, monk, and ojo agents, download a report, you end up with 3 jobs. The upload part becomes a job with ununpack and adj2nest agents in it. The scan becomes the second job with 3 agents running inside it. And the report generation becomes the third job with the report agent running inside it.
Since there is too much info inside a job, the job name is the upload name to simplify things down.

Now if one of the agent fails, lets say nomos, since we are showing all the three agents inside a single job, with the current structure it is impossible to denote what failed, so we mark the whole job as failed.

As a solution, we would have to expand the data sent by the `/jobs` endpoint to something like:
```
{
  job: <id>,
  upload: <id>,
  user: <id>,
  group: <id>,
  jobs: [
    {
      queueId: <id>,
      name: <agent name>,
      status: <queued|running|failed>,
      queueDate: <timestamp>,
    },
    ....
  ]
}
```

There is an issue for that: #1301 
I believe by doing so, current issue will be fixed as well. What do you think @SrikanthShyamanur and @DineshDevarajan ?

**Comment by SrikanthShyamanur** [comment]
@DineshDevarajan 

Consider below upload 

![image](https://user-images.githubusercontent.com/58924156/96684424-2c5abc00-1399-11eb-8851-045db59372f8.png)

By seeing above screen shoot we can conclude. (Lets not consider spdx2 generation, Job/Dependency: 1860)

1. Upload is successful
2. Agents analysis has failed (as monk has failed ) 


Same when queried from _{{baseUrl}}/jobs?upload=266_ will get below json. We would not be able to conclude anything as all the names are same , because I believe **name** is not holding  **<agent name>**.

```
[
    {
        "id": 827,
        "name": "xxxxxxx_PT_V2MIB_LINUX_200916.zip",
        "queueDate": "2020-10-06 13:19:22.219651+00",
        "uploadId": "266",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    },
    {
        "id": 828,
        "name": "xxxxxxx_PT_V2MIB_LINUX_200916.zip",
        "queueDate": "2020-10-07 03:21:40.088122+00",
        "uploadId": "266",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    },
    {
        "id": 829,
        "name": "xxxxxxx_PT_V2MIB_LINUX_200916.zip",
        "queueDate": "2020-10-07 05:14:22.25271+00",
        "uploadId": "266",
        "userId": "3",
        "groupId": "3",
        "eta": 0,
        "status": "Failed"
    }
]

```
 And I agree with the solution specified by @GMishx , which will fix this issue.

**Comment by DineshDevarajan** [comment]
@GMishx  I will enhance the jobs endpoint with job queue details as per the  json provided . Can we create a Feature request for this ?
So if we enhance the /jobs end point response , the fix for #1805 PR = #1812  is not needed ?

**Comment by GMishx** [comment]
That will be great! Can you please use #1301 as the feature request instead?
And please feel free to enhance the JSON data structure. I just wrote whatever came to my mind at the moment.
For PR #1812, maybe we can have it and merge it after 3.9.0 release and if your new PR is ready before it, then we can close #1812 and merge the new PR instead. How does that sound?

**Comment by DineshDevarajan** [comment]
That Sounds Great . I will start to work on enhancing the JSON response for /jobs end point.
