### ISSUE TITLE
delagent failed when delete big iso when didn't set NOKILL option

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#200]
---

Author Name: **Dong Ma** 
Original Redmine Issue: 3525, http://www.fossology.org/issues/3525
Original Date: 2012/09/23
Original Assignee: Mary Laser

---

If not set NOKILL option, when delete big iso will cause delagent fail.

Error log:
2012-09-23 12:19:01 delagent [0] :: JOB[61].delagent[31831.localhost]: received: "HEART: 0 0"
2012-09-23 12:19:16 delagent [0] :: JOB[61].delagent[31831.localhost]: agent has not set the alive flag in at least 10 minutes, killing
2012-09-23 12:19:17 delagent [0] :: JOB[61].delagent[31831.localhost]: agent was killed by signal: 9.Killed

If set NOKILL option, delagent success.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:48 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
review required

**Comment by max-wittig** [comment]
delagent has no 'NOKILL' option. Does anybody know what the issue is or can this be closed?
<pre>
Usage: ./delagent [options]
  List or delete uploads.
  Options
  -i   :: Initialize the DB, then exit.
  -u   :: List uploads IDs.
  -U # :: Delete upload ID.
  -f   :: List folder IDs.
  -F # :: Delete folder ID and all uploads under this folder.
          Folder '1' is the default folder.  '-F 1' will delete
          every upload and folder in the navigation tree.
  -s   :: Run from the scheduler.
  -T   :: TEST -- do not update the DB or delete any files (just pretend)
  -v   :: Verbose (-vv for more verbose)
  -c # :: Specify the directory for the system configuration
  -V   :: print the version info, then exit.
  --user|-n # :: user name
  --password|-p # :: password

</pre>

**Comment by mcjaeger** [comment]
I think the delagent uses the nokill option of the scheduler, but not offering it
