### ISSUE TITLE
Facility to upload folder to fossology

### ISSUE THREAD

**Issue by sameer1046** [fossology/fossology#2006]
### Description

Currently fossology support file upload functionality.
When a folder has lot of components u need to upload one by one.

#### Steps followed and expected result
in upload tab there should be one feature to process the uploaded compressed file as a folder and after uploading that, a parent folder should be created and all files inside that folder should be processed as files accordingly.

**Comment by GMishx** [comment]
We had a discussion on the issue and finalized that instead of letting FOSSology create folders based on archive content (which can lead to unwanted results for person unaware of it), ability to provide multifile upload will be better. Doing so, user can create folders as they need and then upload multiple files at once using the web UI or REST API.
