### ISSUE TITLE
Very slow in loading the license browser page

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2018]
### Description
i recently upgraded to latest version of fossy 3.10.0

the license browser page was loading very slowly. check below gif screenshot

should i do the maintenance ? as mentioned here https://github.com/fossology/fossology/issues/1279?
if so how long it will take ? days or hours?

#### How to reproduce
upgrade the existing production server with lots of previous uploads to latest version via docker method. 
#### Screenshots

![fossy error](https://user-images.githubusercontent.com/4498415/122412396-ce14c600-cf85-11eb-9b32-734df34574bc.gif)

### Versions

* Last commit id on master: Version: [3.10.0], Branch: [HEAD], Commit: [#07f8e5] 2021/05/07 09:49 UTC built @ 2021/06/08 23:08 UTC 
* Operating System (lsb_release -a): Ubuntu 18.04.5 LTS

**Comment by GMishx** [comment]
Hello @dineshr93 , I guess this is due to large amount of data change (since you recently upgraded the version). The maintenance will definitely help, specifically the reindexing and vacuum analyze.

> if so how long it will take ? days or hours?

It takes approx 4 hours for a database 250 GB in size. So about 1 hour per 60 GB of DB (Admin > Dashboards > Overview).
It is highly advisable to run it when no one is using the server as the maintenance is a heavy job on its own.

**Comment by dineshr93** [comment]
It is now speedy. Thanks

**Comment by dineshr93** [comment]
Hi @GMishx 

we just updated to https://github.com/fossology/fossology/releases/tag/4.1.0

we have the same problem now even after doing the maintenance job. May I have your help again please ?

![image](https://user-images.githubusercontent.com/4498415/191683891-7e46f7cb-003d-4d35-918d-c3756edc9803.png)


We have this

**Comment by dineshr93** [comment]
Hi @dineshr93  we observed that if there is any scan jobs in the background while running mainetance job, then it doesnt help in speed up the loading. We tried again maintenance job when there is no scans it worked.
