### ISSUE TITLE
Password change with API

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#2039]
Hi,

Is it possible to change the user password via API?
I have tried this step in postgresql, but when I wanted to login with new pass, fossy gave me back this message:
`The combination of user name and password was not found.`

The way what I have tried to change fossy user password:

```
# echo -n "pass" | openssl sha1
(stdin)= 9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684
# su postgres
# psql fossology
# fossology=# UPDATE users SET user_pass = '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684' where user_name= 'fossy';
UPDATE 1
```

Any idea for the automatization for this step?

Thanks,

**Comment by GMishx** [comment]
Hi @C1ph3R-s , unfortunately updating password is not that straight forward. Currently, FOSSology supports 2 methods to store passwords in DB
1. Salted SHA1 (upon next login, will be changed to second stronger method)
2. BCrypt (stronger the SHA1 for storing password)

To store password in SHA1, you need to first generate a salt (random text) and prepend it to password like `echo -n "thiswillbemysaltpass" | openssl sha1`. Then update the table with `UPDATE users SET user_seed = 'thiswillbemysalt' AND user_pass = '2f1b24e3153fc839357e36b46c86677e159d1d9a' WHERE user_name = 'fossy';`

Otherwise generate password as bcrypt hash (in `$2y$` format) using some tool [like this](https://bcrypt.online/) and cost = 10. Then update the table with `UPDATE users SET user_seed = 'Seed' AND user_pass = '$2y$10$WCmPDzO/0FMKqUFPGuinXOPjlG3KwSqu/miHR7tIxzG9/SnhX8RO2` WHERE user_name = 'fossy';`

If you still have access to the UI, simply goto "Admin > Edit user account" and update password from there.

**Comment by C1ph3R-s** [comment]
Unfortunately it is not working. After I have changed the pass the GUI did not work with it. So I cannot login with the new pass.
Do you have any idea for that?

**Comment by GMishx** [comment]
Can you please try following?
1. Take a salt as `1ef3qwe`, or some other random character.
2. Keeping password as `fossy`.
3. Calculate checksum with "salt+password"
    - `echo -n "1ef3qwefossy" | openssl sha1`
    - hash: `609d2b673fd823a483fb9ce7e2817cb737d1e11e`
    - Note, there is no character between salt and password
4. Update the values in DB, replace `salt`, `hash` and `username` accordingly
    - `UPDATE users SET user_seed = 'salt', user_pass = 'hash' WHERE user_name = 'username';`
    - Example: `UPDATE users SET user_seed = '1ef3qwe', user_pass = '609d2b673fd823a483fb9ce7e2817cb737d1e11e' WHERE user_name = 'fossy';`

You can use the query from point 4 directly to update `fossy` user's password to `fossy`.

Please share which version/commit you are on.

**Comment by C1ph3R-s** [comment]
it has worked very well, thanks.
