### ISSUE TITLE
Uploaded zip file is not recognized

### ISSUE THREAD

**Issue by DimpoCpp** [fossology/fossology#2125]
### Description

I am uploading a zip file, [OpenCV](https://github.com/opencv/opencv), to test it on Fossology. 
I am getting "no file selected" when doing so. 
I have tried using smaller files and it works.
Trying to single out a specific folder, in OpenCV, by extracting and zipping it into a new .zip file, also works.
What could be the reason for this ? Size ? 

#### How to reproduce

Upload the opencv.zip

#### Screenshots

![Screenshot from 2021-12-17 17-08-20](https://user-images.githubusercontent.com/46501122/146573960-843a2f75-914f-4536-9299-1d2621d34d12.png)

**Comment by GMishx** [comment]
![image](https://user-images.githubusercontent.com/18077542/148330640-402f643b-f8e6-43b7-a035-ecd2196409b6.png)

I just tested the upload and it seems to be working.

Can you please provide more info like:

- Apache's error log and access log (available under `/var/log/apache2/` in Ubuntu/Debian)?
- Try capturing the `POST` request from your browser using Web Developer Tool (or what your browser supports)?
- What happens if your try to upload the file two times in a row?
- What is the upload size limit available on upload page?
![image](https://user-images.githubusercontent.com/18077542/148330867-989c9a38-e1b3-42df-be81-e0d35b515890.png)

**Comment by NicolasToussaint** [comment]
Also tried, works well

It could also be a file permission problem ?
That's the message I get when trying to upload a file for which my current user has no `read` permission.

**Comment by GMishx** [comment]
Closing the for now. Please reopen if issue persists @DimpoCpp
