### ISSUE TITLE
oidc auth does not work

### ISSUE THREAD

**Issue by sseneca** [fossology/fossology#2229]
### Description

If I fill out the necessary boxes for oidc in Fossology's web UI and try to login with it, I see this error

> Signature verification failed 

All the values in the web UI are correct as far as I can tell, but the JWT is invalid - https://jwt.io/#debugger-io agrees, with this error:

>  invalid signature
> Looks like your JWT payload is not a valid JSON object. JWT payloads must be top level JSON objects as per https://tools.ietf.org/html/rfc7519#section-7.2

#### How to reproduce

- Fill out boxes for oidc auth
- Try to login

### Versions

* v4.1.0 docker image
* Operating System (lsb_release -a)

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

#### FOSSology logs

None

#### Apache logs

None

**Comment by kannan1997** [comment]
Hi @GMishx, 

Instead of Using 
`$jwtToken = $accessToken->getToken();`
https://github.com/fossology/fossology/blob/4.1.0/src/www/ui/page/HomePage.php#L177

Can we use 
`$jwtToken = $accessToken->getValues() ['id_token'];`  ?

We were facing the above issue while validating the signature. 
This workaround helped to fix the issue. 

Tried on 
Fossology Version: 4.1.0 
Provider: Azure Active Directory. 

Please share with us if you have a better option or permanent solution to fix this issue.

**Comment by GMishx** [comment]
Hello @kannan1997, I am not very sure it will help. Is it possible to send a JWT token for inspection?

You might also wanna check id parameter here: https://github.com/fossology/fossology/blob/871739e03281e9cfe1ae76dd79beebd98d632d5e/src/www/ui/page/HomePage.php#L138

This is the key used for email in JWT token.

**Comment by kannan1997** [comment]
Hi @GMishx , 

Please find the observation below, 

1, "**Signature verification failed**" for [accessToken:protected], but able to verify the signature for [id_token]


Unable to validate the signature via jwt.io for [accessToken:protected] (please find the below code block for more details)

### Please find the Structure(value) found inside $accessToken
https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L152
```
League\OAuth2\Client\Token\AccessToken Object
(
    [accessToken:protected] => <<removed the accessToken (for security reason) which was shown right here>>   ===> Unable to validate the signature via jwt.io
    [expires:protected] => xxxxxxxxxx
    [refreshToken:protected] =>
    [resourceOwnerId:protected] =>
    [values:protected] => Array
        (
            [token_type] => Bearer
            [scope] => email openid profile
            [ext_expires_in] => xxxx
            [id_token] => <<removed the id_token (for security reason) which was shown right here>>		===> Able to validate the signature via jwt.io
        )
)
```

Error occurred exactly here. 
https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L178

**Error Message:  (showed in UI)** Signature verification failed
Note: No error log from back End.

To call [id_token], we can use `$jwtToken = $accessToken->getValues() ['id_token'];`
 
Tried on
Fossology Version: 4.1.0
Provider: Azure Active Directory

---

2, Question from my side, 

When you're trying with different provider, were you able to Validate the signature via jwt.io and also, did the signature verified (this step)
https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L178

---

3, Only Limited details showed in $resourceOwner

https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L198

Even optional Claims didn't helped us. Currently, Email is used as username. 
`We are looking for UPN parameters as username.`


```

League\OAuth2\Client\Provider\GenericResourceOwner Object
(
    [response:protected] => Array
        (
            [sub] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            [name] => <name>
            [family_name] => <family_name>
            [given_name] => <given_name>
            [picture] => <picture>
            [email] => <email>
        )

    [resourceOwnerId:protected] => email
)
```

Can we use this `$jwtTokenDecoded->upn`  inside function `getEmailFromResource`
same like https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L178

instead of using  
https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/HomePage.php#L200

---

4, Can you please throw some light on this  (https://github.com/fossology/fossology/issues/2229#issuecomment-1208079816)

```
You might also wanna check id parameter here:

[fossology/src/www/ui/page/HomePage.php](https://github.com/fossology/fossology/blob/871739e03281e9cfe1ae76dd79beebd98d632d5e/src/www/ui/page/HomePage.php#L138)

Line 138 in [871739e](https://github.com/fossology/fossology/commit/871739e03281e9cfe1ae76dd79beebd98d632d5e)

 "responseResourceOwnerId" => "email", 
This is the key used for email in JWT token.
```
**Note**: Even after Changing Email to id, Signature Validation failed 

https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/GenericProvider.php#L79

**Comment by GMishx** [comment]
Thanks for the info provided @kannan1997 , I have made the fields configurable in https://github.com/fossology/fossology/pull/2305

From your last comment:
1. The field is now configurable. You can use either access token or id token for authentication.
2. I tried mainly with 2 providers. One is internal to my company and other is oauth.com and they worked for me.
3. I am not sure that will be helpful. We are using the `userinfo` endpoint to gather information about the user and make sure it works as we can not rely on access or id token to contain all values. You are free to do your implementation :-)
4. The comment allows you to configure the field to be used as ID in resource owner response. The field is also now configurable.

**Comment by kannan1997** [comment]
Thanks for considering my suggestion. (https://github.com/fossology/fossology/pull/2305)

Please find the suggestion on point (3) and (4).

In my Opinion, [2305](https://github.com/fossology/fossology/pull/2305) change may help in accessing in both accessToken and idToken, but due of limitation in external library GenericResourceOwner, it only provides below value, but not "upn". 

*Note:* Even though, i have claimed upn in azure claims, it didn't help due to limitation of library. 

- https://github.com/fossology/fossology/pull/2305/files#diff-4c30f62c3f3dd605637bc2d8931fb1e216063ae5b536aad0127a61afdc4eb502R138
- https://github.com/fossology/fossology/pull/2305/files#diff-24724248fe452296b11be6a8423331269089b3057511f90db0de4babb0b6eb33R204

Only limited parameters are available.

```
League\OAuth2\Client\Provider\GenericResourceOwner Object
(
    [response:protected] => Array
        (
            [sub] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            [name] => <name>
            [family_name] => <family_name>
            [given_name] => <given_name>
            [picture] => <picture>
            [email] => <email>
        )

    [resourceOwnerId:protected] => upn             ===> upn is not available in above Object)
```
Can i raise a new PR to fetch ```$SysConf['SYSCONFIG']['OidcResourceOwnerId']``` from the Token on top of [2305](https://github.com/fossology/fossology/pull/2305)?
