### ISSUE TITLE
Add GitHub Bots to fossology repositories 

### ISSUE THREAD

**Issue by Ayush7614** [fossology/fossology#2234]
Here is the list of GitHub Bots that can integrate at the beginning:
https://docs.google.com/document/d/1awz3U5ed9fLH4wWUhWrLsJ03f0PWMu48cmvvorfLBs4/edit?usp=sharing

We need to have project-specific bots later (Especially for Python and JS-based projects) to track code quality, builds and all. Please have a look and let me know what you think. You can also add more bot integrations that we can have right here.

This issue would be used to track the integration of GitHub Bots across [fossology](https://github.com/fossology/fossology) repositories.

**Comment by avinal** [comment]
The CI workflows have already been implemented here #2075. It may be beneficial to use a stale bot and DCO bot, rest I don't think there is much use for us.

**Comment by Ayush7614** [comment]
> can you please provide suggestion permission on the above shared link?

Already Done @GMishx Sir

**Comment by GMishx** [comment]
> Github Bots and Githubs Actions for Fossology Repos
> 
> 1- Prosebot - a. Checks for grammatical errors in the Docs. b. Analyzes spelling, prose and inclusive verbiage in Markdown and Text Files. c. Provides an easy way to analyze documentation changes and ensure a consistency throughout

Can be good. But should be carefully looking only for docs and not code. Otherwise there will be many false positives.

> 2- Stale Bot- a.Closes Issues and Pull Requests if not attended to in a specified period of time... b. Maintains the overall sanctity of the Issues and Pull Requests tab. c. Keeps a check on spam/unnecessary Issues and PRs

It is not required in my opinion for our repos.

> 3- Request Info a- Requests for information if the Issue/PR content body is empty. b- Helps us mitigate spam/invalid Issues and PRs.

Will be good.

> 4- DCO a. Enforces Developer Certification of Origin on Pull Requests

Can be used.

> 5-Greetbot a . Greets first-time contributors.

Not needed in my opinion but would like to go with what others say.

> 6. CI Workflow
>   Adds CI workflow to build and validate the build

Don't we already have it for almost all repos?

> 7. Add a GHA workflow for lint and build

Don't we already have it for almost all repos?

> 8. lighthouse CI - for tracking web performance

Where will it be helpful?

> 9. Add a GHA workflow for lint and build

Don't we already have it for almost all repos?

> 10. Codecov - Outputs Code coverage results (but would need github actions to be set)

Don't we already have it for almost all repos?

> 11. Adds an action to install, build and store the build as an artifact

Don't we already have it for almost all repos?

> 12. Adds a workflow step to put up a GitHub comment on respective PRs after deploying

Where will it be helpful?
