### ISSUE TITLE
investigate scanning java repositories to find jar licenses

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#239]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 5877, http://www.fossology.org/issues/5877
Original Date: 2013/09/26
Original Assignee: larry shi

---

My thought was that a new agent could scan a list of sites, like maven, to find declared jar licenses.  This issue is just to answer the question - would this be difficult to implement?

**Comment by mcjaeger** [comment]
the feature would require a more elaborate description. Is it that an artifact server could be batch scanned by Fossology one a root URL to the artifacts is provided?

**Comment by bobgob** [comment]
Java apps frequently have dependencies outside of developer source control systems.  For example, they might have a dependency on something pulled from maven.  The idea behind this investigation is to resolve licenses pulled in by these dependencies.

**Comment by mcjaeger** [comment]
Yes, that I got about maven, but how should this work from a fossology point of view -

+) "agent scan list of sites"? - shall Fossology fetch the artifacts from the maven artefact  server, was that "site"?

*) how should such feature look like? Like upload from URL or upload from source (which you could do today already, because most dependencies have an URL provided by the artifact server.

I am just not seeing what to design / code / build from this ticket so far.
