### ISSUE TITLE
nomos can not report licenses correcly

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#243]
---

Author Name: **larry shi** 
Original Redmine Issue: 6069, http://www.fossology.org/issues/6069
Original Date: 2013/11/20
Original Assignee: larry shi

---

Not sure should report Apache-2.0 or 1.1?

should report GPL-2.0-with-classpath-exceptions, not GPL-2.0+-with-classpath-exception, little difficult to fix.

it is difficult to fix this combined file, will try to find a solution for this style case.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4509/openjdk-7-jre-headless_license.txt

**Comment by mcjaeger** [comment]
attached a screenshot hwo it looks today (with some wrongly identified licenses).
![monos 2015-08-28 21_06_35-change concluded license](https://cloud.githubusercontent.com/assets/3418977/9554780/b5a70870-4dc8-11e5-8dc3-49828ea1f505.png)

In general it is not obvious to me if that is a bug, because from my point of view:

* nomos does not identify the real license -> lack of performance
* nomos does not see that a license info is in the file -> bug.

**Comment by bobgob** [comment]
I don't follow you @mcjaeger   The issue asked two questions.  One around Apache 2 vs 1.1 and the other around GPL.  It looks like nomos incorrectly identified Apache 2 instead of 1.1, but correctly  got GPL-2.0-with-classpath-exception
Did I miss something?

**Comment by mcjaeger** [comment]
@bobgob I changed the ticket category / tag from bug to enhancement, because of my given idea above. Just wanted to make the point that a bug in Nomos would be IMHO if a license is ignored.

**Comment by silverhook** [comment]
When it comes to `GPL-2.0-with-Classpath-exception`, shouldn’t it now be reported as `GPL-2.0 WITH Classpath-exception-2.0` instead?

**Comment by mcjaeger** [comment]
Hi,

yes.

no seriously: fossology uses the deprecated license Ids from the SPDX license list and we were hesitant to change the license short names (in fossology speak it is called short name, what is the SPDX license id) because we have so many results out there which would be invalidated.

But the best way would be to modify fossology to implement the “WITH” operator along with the “AND” and “OR” operators. There is an issue for that [1]

Kind regards, Michael

[1] https://github.com/fossology/fossology/issues/687

**Comment by mcjaeger** [comment]
new test file uRL is here:
http://archive15.fossology.org/attachments/download/4509/openjdk-7-jre-headless_license.txt

Looks at the file:

1. Apache 1.1 is in somehow, so reported and is OK.
2. apache 2.0 is in the file mentioned, so reported and thus OK.
3. statement about GPL-2.0 with classpath exeption is there, but also GPL-2.0-only reporting is there, so the experts is advised to clarify what to do here.

I think exception and the notion of `only` and `or later` will be changed anyway in future, so closing ...
