### ISSUE TITLE
Issue while inserting new token key in Fossology Version 4.4.0

### ISSUE THREAD

**Issue by Abilash18** [fossology/fossology#2687]
**Issue Description:**

There is an issue with a token in Fossology Version 4.4.0. The problem arises when newly created tokens and active access tokens do not match.

**To reproduce this issue:**
1. Create a test instance for Fossology version 4.4.0 by downloading the latest image from the Docker Hub.

**docker run -id -p 8033:80 fossology/fossology:4.4.0**

2. Verify that the instance is running by checking the Docker processes.

**docker ps | grep 8033**

3. Login to the Fossology server at http://localhost:8081/repo/ using the credentials:

    Username: fossy
    Password: fossy

4. Create a new token for the user account.
5. Reveal the active access token.
6. Compare the active access token with the new token for Bearer authentication. 

we observed there is a difference between the token in 4.4.0 whereas it's the same in the previous version 4.3.0.

Please let us know the actual use case.

**Comment by dvjsharma** [comment]
Hey Abilash, I reproduced the issue in both V 4.4.0 and V 4.3.0 releases, below are the results

_V 4.4.0_
![Screenshot from 2024-02-23 01-14-39](https://github.com/fossology/fossology/assets/119073504/d75b081b-229a-4daf-a942-019716740dc2)

_V 4.3.0_
![Screenshot from 2024-02-23 01-43-58](https://github.com/fossology/fossology/assets/119073504/fd7ac3a3-ce40-4303-b74c-0e90ca4e3bf7)
 
For me, the tokens differ in both releases, and ideally they can vary since generated JWT tokens are authenticated using a secret string. Therefore, multiple tokens can coexist at a given time, each granting authentication access. Please take a look and confirm if I am understanding your issue accurately.

**Comment by Abilash18** [comment]
Hi @dvjsharma 

This issue was working as expected in the latest version of Fossology 4.4.0.

Thanks for the support.
