### ISSUE TITLE
Uploading a new file to Fossology server via API v2

### ISSUE THREAD

**Issue by seaykut** [fossology/fossology#2704]
### Description

I'm trying to upload "file.tar.gz" file to Fossology server via API v2 and using the API yaml below;

https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapiv2.yaml

The problem is, I can not find any "file" or something like that on req body data in "Uploads" section.

So I'll use the curl command to send the file for analyzing but not sure how to select/choose the local "file.tar.gz" file.

#### Screenshots

![image](https://github.com/fossology/fossology/assets/92121932/753ac8a1-ff14-4f11-9108-da8faedf4534)

![image](https://github.com/fossology/fossology/assets/92121932/8823947e-7921-4d2b-ac9e-5095022b02b8)

### Versions

    Fossology ver : 4.4.0.11
    Ubuntu 20.4

**Comment by dvjsharma** [comment]
Hello @seaykut, 
The example schema is only written for `vcs`, `url` and `server` upload types. Please refer [this](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapiv2.yaml#L731-L733). Regarding the `file` upload type, it makes more sense if user can directly choose file in their local machine, which doesn't really require a schema. In your case, please change the request body type to `multipart/form-data` from the drop down menu, which is designed to handle `file` type uploads.

**Comment by seaykut** [comment]
@dvjsharma thanks for the message but still not clear for me. If I set "-H  "Content-Type: multipart/form-data" \", then I have to set "-F "uploadType=file", and then it should be ok?
But is this how it is supposed to be? I mean "uploadType=file" is not declared on API v2 yaml file.

**Comment by dvjsharma** [comment]
Hey @seaykut, regarding your previous comment, I've checked the API v2 yml file and you are correct; the request doesn't include the required `uploadType` information (for ` multipart/form-data`), as per the controller logic. I would recommend using the API v1 yml file until we have completed the migration to v2. Even if you send a v2 request using the v1 yml file, it won't work as expected because we need all the parameters in the request body rather than in the headers. The file that was changed during the migration of the `/upload` API to v2 was `openapiv2.yaml`, so the changes aren't there in the v1 yml file. (#2634)

**Comment by seaykut** [comment]
@dvjsharma thanks for the info. Somehow I'm able to upload the file to the Fossology server with the command below;

```
curl -X POST "http://10.10.10.10:8081/repo/api/v2/uploads" \
     -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIU" \
     -F "fileInput=@/home/repos.tar.gz;type=application/gzip" \
     -F "folderId=3" \
     -F "uploadDescription=license" \
     -F "public=public" \
     -F "groups=groupName" \
     -F "uploadType=file"
```

Should I continue to my project with this command or should I change completely to API v1?

**Comment by dvjsharma** [comment]
Yes, that should work fine. I've also submitted a pull request addressing this issue, which will fix the problem in the v2 YAML file as well. Regarding which version to choose? As of now, I recommend sticking with v1 due to its consistent workflow. The migration to v2 isn't complete yet. Maybe @GMishx can add more to this.

**Comment by GMishx** [comment]
Hey @seaykut, as @dvjsharma mentioned, the migration to v2 is not complete. I will recommend to continue with v1 till the migration to v2 is complete.

Also, if you are writing a program to interact with FOSSology's API, there is [fossology-python](https://fossology.github.io/fossology-python/) project which is the most complete Python library to communicate with FOSSology's API. You can also look into it.
