### ISSUE TITLE
any user who is not the owner can delete any folder via /delagent -F

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#273]
---

Author Name: **larry shi** 
Original Redmine Issue: 6741, http://www.fossology.org/issues/6741
Original Date: 2014/03/18
Original Assignee: Dong Ma

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/18 17:42:39 +0000

---

We are past the 2.5 code complete date, so moving to 2.6.

**Comment by mcjaeger** [comment]
should have been made a common ticket with #272

**Comment by maximilianhuber** [comment]
maybe related to #368

**Comment by shaheemazmalmmd** [comment]
Folders are not linked with users in database model. any user above write permission can create a folder and delete it except "root folder" of him from UI, But from command line he can delete his root folder as well. i think we need to link user_fk to folder table or foldercontents to restrict other users. ?? but if the group admin is deleting it then he cant because he is not a owner. 

or the user with top level folder access can delete his child's not all folders he doesn't belongs to ??

**Comment by maximilianhuber** [comment]
related to / same as 
* #186 and
* #1293 (in the old bug-tracker)
