### ISSUE TITLE
Freeze functionality works not well

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#278]
---

Author Name: **larry shi** 
Original Redmine Issue: 6795, http://www.fossology.org/issues/6795
Original Date: 2014/03/21
Original Assignee: Bob Gobeille

---
1. freeze on side, the caption is changed to 'Frozen, Click to unfreeze'
2. click another side, frozen side works well, however, the caption is wrong, should still 'Frozen, Click to unfreeze', not 'Freeze path'

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/21 16:09:20 +0000

---

I assume you are reporting this problem for both license and bucket diffs since they use similar (and shared) code.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/24 02:32:08 +0000

---

Bob Gobeille wrote:
> I assume you are reporting this problem for both license and bucket diffs since they use similar (and shared) code.
yes

**Comment by mcjaeger** [comment]
Am not sure what freeze means, but if it is about "unpause" in job view it seem to work (apart fro the title) - so, close please if freeze means "pause" in job view.

**Comment by bobgob** [comment]
This refers to the license and bucket compare features, not a job pause.
When you are doing a compare it looks like an sdiff (side by side diff).  The program tries to intelligently align the sides and when you traverse the file tree on either side the opposite side will try to align correctly.  If that doesn't happen correctly, you can "freeze" one side of the diff while traversing the other in order to get them aligned again.

**Comment by mcjaeger** [comment]
tested with `Version: [3.4.0], Branch: [master], Commit: [#6ad6a1]`, I can freeze, but the freeze is lost after one page releoad. So this is not working perfectly, but I think at least the issue seems to be solved as described.
