### ISSUE TITLE
"Require location object if uploadType != file" / "Require uploadType" errors when uploading a file

### ISSUE THREAD

**Issue by romayankin** [fossology/fossology#2810]
### Description

I am trying to upload a file either from local drive or from URL using python script but I get errors in either scenario:

I have tried both v1 and v2 APIs and none of them work for me

This is the code I use:

```
def uploadPackageFromURL(url, folderId = 1):

    PAYLOAD = {
            'folderId': str(folderId),
            'uploadType': 'url',
            'uploadDescription': 'Uploaded by script',
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {__TOKEN__}'
        }

    fileName = extractArchiveNameFromYarnPkgURL(url)
    fileContent = getFileContentFromURL(url)

    with open(__TEMP__, 'wb') as uploadFile:
        uploadFile.write(fileContent)
        uploadFile.close()

    with open(__TEMP__, 'rb') as uploadFile:
        if fileContent != 0:

            
            # Define the files parameter for the upload
            files = {
                'fileInput': (fileName, uploadFile, 'application/octet-stream') 
            }

            dataRaw = {
                "url": url,
                "name": fileName
            }
            
            # Make a POST request to the API and upload the file
            response = requests.post(__URL__ + '/v1/uploads', files=files, data=dataRaw, headers=PAYLOAD)
            
```

#### How to reproduce

You can use this URL: https://registry.yarnpkg.com/@ampproject/remapping/-/remapping-2.3.0.tgz#ed441b6fa600072520ce18b43d2c8cc8caecc7f4

and run the above script to see issue, which is this:

If the **uploadType** is set to 'url' I get this error:

```
/scripts/foss/.venv/bin/python /scripts/foss/scanURL.py yarn.txt
Failed to upload file. Status code: 400
Response: {"code":400,"message":"Require uploadType","type":"ERROR"}
```

If the **uploadType** is set to 'file' I get this error:

```
Failed to upload file. Status code: 400
Response: {"code":400,"message":"Require location object if uploadType != file","type":"ERROR"}
```

### Versions

I use FOSSology v4.4.0.63

**Comment by romayankin** [comment]
@tiegz @kad @erikd @AlanHohn apologies for summoning you guys but do you have any idea on what am I doing wrong?

**Comment by erikd** [comment]
Sorry, no idea. I have not even looked at this software in over 8 years.

**Comment by dvjsharma** [comment]
Hi @romayankin. There are minor bugs in your script: `folderId` should be an integer, and `content-type` must be `application/json` for `url` upload types; otherwise, use `multipart/form-data` for `file` upload types. Please check the [OpenAPI documentation V1](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml) for the latest API details, which may help resolve these issues. You can also get the `curl` commands by running this file through [Swagger UI](https://editor.swagger.io/).

Version 2 for reference - [OpenAPIV2](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapiv2.yaml)
Content type discussion - #2735 
Similar issue - #2708

**Comment by shaheemazmalmmd** [comment]
@romayankin As there is no reply from you we consider that the issue is closed. please reopen if there are any further questions.
