### ISSUE TITLE
Agent update with vacuum and analyze

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#283]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6843, http://www.fossology.org/issues/6843
Original Date: 2014/03/27
Original Assignee: Dong Ma

---

I think we should not depend on a properly configured postgresql server to do auto vacuum and auto analyze.  So after an agent does significant updates to a table, they should run vacuum analyze on their main updated table.  This can result in a big performance boost.  Specifically this impacts:

adj2nest
nomos
copyright
delagent
buckets
mimetype

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/28 16:32:46 +0000

---

We should be smart about this though.  There should probably be some threshold number of records written/updated before we do a vacuum analyze.

**Comment by GMishx** [comment]
The `VACCUM ANALYZE` is taken care by the `maintagent`. Since these tasks require high CPU time, it should not be ideal to run them very frequently that too on a server with active users.

The best solution should be to create a cron job and run the maintagent weekly (or daily as required) when the server is at minimum load.

A sample cron job which run every Sunday at 02:00 A.M.

```cron
0 1 * * Sun /etc/fossology/mods-enabled/maintagent/agent/maintagent -D -I 2>&1 | tee -a /var/log/fossology/maintenance.log
```
