### ISSUE TITLE
number. Of items processed is zero even though there are scanoss results

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#2855]
### Description

number. Of items processed is zero even though there are scanoss results in a upload.

it will confuse fossology users as most of them will look in to processed item count to identify if there are any findings.

#### How to reproduce

* Upload any package and select scanOSS agent for scanning.

#### Screenshots

![screenShot144](https://github.com/user-attachments/assets/bedecc70-f2c4-4f6e-a0c6-1a7c2ee0d158)

**Comment by yours7himanshu** [comment]
I think i can solve this issue

**Comment by Vaibhavsahu2810** [comment]
I've been troubleshooting this issue . Here’s a summary of the steps I've taken so far:

Initial Logging in src/scanoss/agent/snippet_scan.c and src/scanoss/agent/main.c: I added detailed logs to verify that scanning is completed properly. Based on the logs (see attached image), both snippet_scan.c and main.c appear to perform scanning as expected, indicating these components are functioning correctly.
![image](https://github.com/user-attachments/assets/407a1c59-0426-4314-b7ad-f0d29f43665c)

Job Queue Verification: I next verified whether agent_scanoss was correctly adding jobs to the job queue in database. However, as shown in the second image, the jobqueue table doesnot have proper data.
![image](https://github.com/user-attachments/assets/1f0703d6-da4c-442a-b78d-927b35bb8dc2)

Root Cause Analysis: After further investigation, I found that the AgentAdd function was missing in src/scanoss/ui/agent-scanoss.php. This function is essential as it calls doAgentAdd, which is responsible for adding scan information to the job queue table. I went ahead and implemented the missing AgentAdd function to call doAgentAdd as required.
![image](https://github.com/user-attachments/assets/7668b44c-9580-4e4b-bd83-d605f109165b)

Despite adding the AgentAdd function, the issue persists.

@shaheemazmalmmd  Could you please advise if there might be additional steps or specific configurations I'm missing that could resolve this 
 issue?

**Comment by SalmanDeveloperz** [comment]
Hi, Could you please confirm if this issue is still open?

**Comment by shaheemazmalmmd** [comment]
> Hi, Could you please confirm if this issue is still open?

Issue is fixed.
