### ISSUE TITLE
Reduce UI header footprint and rework

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#286]
---

Author Name: **Silvano Cirujano Cuesta** 
Original Redmine Issue: 6867, http://www.fossology.org/issues/6867
Original Date: 2014/04/07

---

The current UI uses a lot of space on the top of the page that doesn't bring much for the usage of the tool. Reducing that space would be quite useful for people using small screens.

I will split this backlog in two more specific backlogs with proposals.

**Comment by mcjaeger** [comment]
maybe the Ui header needs rework, because some page seem to use different UI headers than others. there seem to be two Ui headers around:

![image](https://user-images.githubusercontent.com/3418977/40611853-5c3cf5fc-6278-11e8-8793-e01b60c7fcb8.png)

and

![image](https://user-images.githubusercontent.com/3418977/40611873-6d0a8ac0-6278-11e8-98da-2bc42329427f.png)

**Comment by Radhey1820** [comment]
Can solve this issue of reducing Header footprint space?

**Comment by shaheemazmalmmd** [comment]
Tested with 4.0.0 the UI headers are in fixed position. Please re-open if the issue persist.
