### ISSUE TITLE
Add "restart" to Show Jobs

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#297]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6945, http://www.fossology.org/issues/6945
Original Date: 2014/04/21

---

Currently Show Jobs allows you to Cancel and Pause.  We should add restart which (unlike the old restart) will queue a new job.

**Comment by mcjaeger** [comment]
is it maybe there ("unpause") - can we close it?

**Comment by bobgob** [comment]
Pause is a temporary pause.  You might do that if an agent is taking loads of resources and you need to get other work done.  Currently after a failure, there are no options.  If the failure was due to something like a network failure it would be very handy to just say "restart" or "requeue".  In other words, you want to run the agent again because the failure wasn't a fossology software failure.

**Comment by mcjaeger** [comment]
this appears to be more complicated then - to make sure that all the agent are kind of "idem potent", so running all agents for >1 has the same desired effect when running successfully. So, duplicating nomos scan findings each nomos run would be bad here.

**Comment by mcjaeger** [comment]
some of the agents may also require user input, needs to considered it would work well only for jobs that take the upload as parameter.
