### ISSUE TITLE
Support license List download 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#334]
---

Author Name: **Johannes Najjar** 
Original Redmine Issue: 7485, http://www.fossology.org/issues/7485
Original Date: 2014/08/21

---

This feature has been suggested by Larry in #7467

license download for monk
on ui, there are 2 menues, | License List | License List Download |, right now, just support for nomos.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/08/21 16:14:00 +0000

---

This is a good idea but needs some thought (see also #7005):

* The nomos "License List" and "License List Download" is very slow.  To run this from the UI it needs to be LOTS faster.  Otherwise, we should run it in through the scheduler.

* Do we add a monk license list or combine the monk/nomos results in the output.  If the later, we need to change the output format.

**Comment by mcjaeger** [comment]
I am also voting for having the license list:
* containing the monk results (and also Ninka) - or maybe the clearing results?
* actually, instead of having two menu items: "License List" and "License List Download" it could be two for download:1. "Scanner License List", 2. "Concluded License List", both for download. It is maybe not necessary to have UI page anymore since the list is also in the License Browser main table in column 2 (and 3).
* could have the same format as used in the license browser table (column Scanner results)
* scheduling could be the same way as readme generation works.

**Comment by bobgob** [comment]
I think these real time options (License List and License List Download) should go away because of the problems mentioned in the issue.

Why not add these to the Browse Action items (with SPDX, Readme_OSS, etc)?
License List Download (containing the combined results from all license scanners)
Concluded License List Download

**Comment by mcjaeger** [comment]
it seems to be implemented
