### ISSUE TITLE
nomos agent is too slow

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#343]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7635, http://www.fossology.org/issues/7635
Original Date: 2014/09/04

---

We really need to speed up nomos.  Program optimizations, parallelization, whatever it takes.  It is our most important agent and it runs way slow.  For example, I typically see it running around 8 items/sec.  That means 28 hours of processing for 800,000 items in an upload.  And we typically see bigger uploads than that.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/09/04 19:44:06 +0000

---

Another tool that would improve nomos performance is the sqlCopy function (fossology/src/lib/c/sqlCopy.c).  This batches db inserts.  Every agent that does a lot of inserts should probably be using this.

**Comment by mcjaeger** [comment]
is an issue, but not super important. still on my Xeon E5 26something with SSD RAID I am in the same area.

**Comment by mcjaeger** [comment]
please consider also (differently explained but same issue) what was written in #326 

"this issue is from #6399
If the nomos performance is just due to adding licenses, then why no change from 2.2 - 2.4? It doesn't seem this is the only cause. If it is then we could speed up nomos a lot by getting rid of the obscure licenses that nomos reports that we have no license reference for.
I will follow up this issue, so the 1st thing is file a new defect for it."

**Comment by mcjaeger** [comment]
closing this one because of unclear requirements
