### ISSUE TITLE
copyright agent 2.5.0: support copyright symbol

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#347]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 7665, http://www.fossology.org/issues/7665
Original Date: 2014/09/08
Original Assignee: larry shi

---

As a simplified version of 7653: please support the copyright symbol. The attached file from the Linux kernel contains this character. It might be good to have it supported as well as it is a *really* good indicator that there is a copyright statement :-)

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4347/scan.c

**Comment by mcjaeger** [comment]
looks like it is supported, retest from ticket opener (because I did not test for this particular file - which may be different encoding as with my example)

![2015-08-25 14_51_14-copyright_email_url_author browser](https://cloud.githubusercontent.com/assets/3418977/9466982/cab34e6e-4b38-11e5-9de2-600796a7b351.png)

**Comment by mcjaeger** [comment]
closing as the copyright sign appears supported
