### ISSUE TITLE
large number of jobs - performance problem

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#364]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 8007, http://www.fossology.org/issues/8007
Original Date: 2014/11/17

---

When there are a large number of jobs (low thousands) the getrunnable() function used by the scheduler can take a few seconds to run.  This query is run every two minutes.  Some possible solutions:

1) Add an option to the maintenance agent to do something like
 @ delete from job where age(job_queued)>'1 yr';@

or
2) speed up the query
Some things that would help this are:
* Make sure when a job fails that jq_starttime is set (not null)
* When an agent fails (like wget) remove all the dependent jobqueue entries

**Comment by steffen-weber** [comment]
Could you please check if this function is faster for a large number of jobs?
```
CREATE OR REPLACE FUNCTION getrunnable2()
  RETURNS SETOF jobqueue AS $$
BEGIN
  RETURN QUERY
    SELECT jobqueue.*
    FROM jobqueue
      INNER JOIN job ON job_pk = jq_job_fk
    WHERE jq_starttime IS NULL AND jq_end_bits < 2
      AND NOT EXISTS(SELECT * FROM jobdepends, jobqueue jdep WHERE jdep_jq_fk=jobqueue.jq_pk and jdep_jq_depends_fk=jdep.jq_pk AND not(jdep.jq_endtime IS NOT NULL AND jdep.jq_end_bits < 2))
    ORDER BY job_priority DESC;
END $$
LANGUAGE plpgsql
```

**Comment by bobgob** [comment]
getrunnable2 looks much faster.  In my tests I'm seeing getrunnable() run in 600-650 ms and getrunnable2() run in ~10ms
My test system has 8981 rows in jobqueue
1713 in the job table
and 8094 rows in jobdepends
I don't have a system with a lot of job records since getrunnable() was taking so long I purged the tables.  This looks like a huge improvement given the 2 second cycle time in the scheduler.
