### ISSUE TITLE
Major Nomos Regression with AGPL

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#388]
There has been a major regression in 2.6.2 concerning nomos scans for AGPL.  It is finding things like "FREE"  see http://www.fossology.org/attachments/4287/ampdu.c
or "gpl" in "gplplaceholder" see http://www.fossology.org/attachments/4281/apps.js

This is a critical defect since it results in many false positives.

**Comment by yaobinshi** [comment]
bob, please help to verify this issue, thanks.

**Comment by bobgob** [comment]
nomos returns "BSD" for apps.js, but the file contains:
'''
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
'''
So shouldn't it return BSD-style or See-file(LICENSE)?

**Comment by mcjaeger** [comment]
I propose to retest for 3.0.0 with current master.

**Comment by mcjaeger** [comment]
Since the "BSD" finding alone doe snot specify a particular license and therefore it can be considered a "BSD-style" I am not seeing a problem newer than the general BSD problem we have. Also the statement says, it is like BSD, see file for details, so "BSD" appears to me a more precise results than "See File"

The original issues are solved, tested with current master results in:
apps.js -> no GPL finding anymore, but kind of correctly "BSD")
ampdu.c -> no FREE finding anymore, but kind of correctly "MIT-style"
