### ISSUE TITLE
Missing report_cache

### ISSUE THREAD

**Issue by steffen-weber** [fossology/fossology#490]
Since commit 7b49ddd176dd73da6752cc1bb9af62fb4171a080, the tables report_cache and report_cache_user aren't used anymore. Hence, the schema and lib/php/common-cache and related code could be cleaned.

**Comment by mcjaeger** [comment]
it looks like they are essential for the following case:

_Testing the license browser on the master branch (#25f4d65) I discovered that there is a very serious performance regression.  My test case was a debian distro with 3.1 M files.  To bring the distro up in the license browser it took over 30 minutes.  That is probably 2x slower than it used to be.  What  is even worse is that hitting the page again also took a very long time.  I didn’t time it and I got tired of waiting.  What happened to the report cache?  Why isn’t it being used?  This is a very serious issue for our users who scan distros._

this could be resolved if the report cache would work for the license browser view. because for very large uploads (the 3.1 mio files) the view is built freshly every call.

I remember that it worked also for license browser view as there.Could you please provide more information or hints what may have pulled the cached view away from the license browser view?

**Comment by bobgob** [comment]
The report cache is still used by buckets, nomos-diff, demomod.
Unless you have a better idea, the lack of the report cache will kill our users who scan distros.

**Comment by mcjaeger** [comment]
changed name from clean up to missing, because it appears like that this actually the issue.

**Comment by mcjaeger** [comment]
There are a few points, flat caching is difficult, because the view depends now on:

* clearing status of directories
* group membership
* plus filters maybe

these are volatile and therefore it appearsdifficult to implement the cache for this license browser hierarchy view. Because this view then would need to store different views per case.

Please could you describe the use case, more importantly, if there is the license decision info required for this kind of browsing? Then, one of the possible solutions could be better narrowed down.

possible solutions:

* implements guessing or approximate information (like cleared files of licensed files info could trun from 5682/10333 to 5600/10000)
* Store aggregations of hierarchy levels
* Purge decision state "open"
* do not look for global license decisions

my personal favorite would be to implement a simple file-scanner-result oriented view that can be easily cached, because once a file was scanned it is pretty much static.

This could be the "normal" browse view, just providing almost the same view as the license browser minus everything with clearing decisions. As such, the caching would not deal with ever ongoing volatility and navigating the hierarchy without caching would notably quicker.

**Comment by bobgob** [comment]
Long term we might want to think about either reorganizing the db or to aggregate all the clearing and state data so that only a single hierarchy level needs to be scanned.  
The filters don't change the data on the rendered page, only the view.
As far as the group membership/permissions goes, that should be checked before the cache file is retrieved so I don't think that's an issue.

**Comment by bobgob** [comment]
Is anyone working on this critical issue?

**Comment by mcjaeger** [comment]
We have scheduled it, as said, not easy to solve. Maybe more news this week.

**Comment by mcjaeger** [comment]
Just to pick up the issue: our current proposal would be to update the browse view (which was unmodified so far) with a simple version of the License Browser file-based table view based  on jquery. Would this work? The advantage would be to have also this corner sorted out again.
But what would be required to display: just the files along with the links / actions and the scanner results - and no clearing decisions?

**Comment by maximilianhuber** [comment]
Here are two screenshots to visualize @mcjaeger's question/suggestion

old:
![browser-before](https://cloud.githubusercontent.com/assets/1187050/10185958/5fcc5b28-674d-11e5-92b8-1720f9ebd842.png)

new (with caching):
![browser-after](https://cloud.githubusercontent.com/assets/1187050/10185964/68c165f2-674d-11e5-8488-b72c86d7d5e4.png)

**Comment by maximilianhuber** [comment]
@mcjaeger's suggestion would look like:

![screen_2015-09-30_11-09-14](https://cloud.githubusercontent.com/assets/1187050/10188985/e6b26ef0-6763-11e5-9cd4-4b7c8cd0b71b.png)

**Comment by maximilianhuber** [comment]
Hi,

i have implemented a Plugin __File Browser__ ([Pull request 534](https://github.com/fossology/fossology/pull/534)) which is supposed to be a faster and lightweight alternative to __License Browser__.
The differences are, that __File Browser__ does not
1. aggregate the information for the license-histogram
2. show any information related to clearing
3. call `getFatItemArray`

#### Example:
Chromium source code: 780MB with 290000 Files

If one opens the root folder of this project with the __License Browser__ the
following happens:

1. The browser fetches `/repo/?mod=license&upload=...`
  * this takes **~4s**, where
    - around **3.6s** of this call are due to the function `createLicenseHistogram(...)` in [ui-browse-license.php#L171](https://github.com/fossology/fossology/blob/master/src/www/ui/ui-browse-license.php#L171).
2. After that, JavaScript requests `/repo/?mod=ajax_explorer&upload=...` (contains the content of the main table)
  * this takes **~9s**, where
    - **~3s** taken by things related to clearing and
    - another **~2.5s** are generated by `uploadDao->getFatItemArray(...)` in [AjaxExplorer.php#L346](https://github.com/fossology/fossology/blob/master/src/www/ui/async/AjaxExplorer.php#L346) which sits in a loop.

The __File Browser__-call only takes **0.4s** for the first request and **2.8s** for the
second and it should not slow down when more clearing decisions are made.

#### Screenshot:
![screenshot0](https://cloud.githubusercontent.com/assets/1187050/10581937/8a66e06e-7685-11e5-876c-750a5c3abe9e.png)


#### More information:
It can be accessed via the drop-down menu in the browse view
![screenshot1](https://cloud.githubusercontent.com/assets/1187050/10581442/fef912a6-7682-11e5-8118-7a092ee2b366.png)
or the micromenu
![screenshot2](https://cloud.githubusercontent.com/assets/1187050/10581450/0728de70-7683-11e5-8f93-1fca67aa2573.png)

**Comment by steffen-weber** [comment]
This patch pushes a rotation file handler for logging performance of the right-hand side table:
```
diff --git a/src/www/ui/async/AjaxExplorer.php b/src/www/ui/async/AjaxExplorer.php
index 9f7895e..be074e9 100644
--- a/src/www/ui/async/AjaxExplorer.php
+++ b/src/www/ui/async/AjaxExplorer.php
@@ -85,6 +85,9 @@ class AjaxExplorer extends DefaultPlugin
    * @return Response
    */
   protected function handle(Request $request) {
+    /* @var $logger \Monolog\Logger */
+    $logger = $GLOBALS['container']->get('logger');
+    $logger->pushHandler(new \Monolog\Handler\RotatingFileHandler('/tmp/ajax-explorer.log',5));
     $upload = intval($request->get("upload"));
     $groupId = Auth::getGroupId();
     if (!$this->uploadDao->isAccessible($upload, $groupId)) {
```
To most expensive stuff w.r.t. /tmp/ajax-explorer-*.log is 
````
query 'CREATE DbView already_cleared_uploadtree19' took 730.791ms
query 'CREATE DbView no_license_uploadtree19' took 456.850ms
executing 'uberItems' took 229.894ms (1 queries, avg 229.894ms)
executing 'Fossology\UI\Ajax\AjaxExplorer::createFileListingORDER BY lft asc LIMIT 50' took 187.739ms (1 queries, avg 187.739ms)
````
for a test case with plugin execution 2101.304ms for me.
Are these entries also the critical ones for the distro example?

**Comment by mcjaeger** [comment]
OK, this is it for now. seems like good improvements. Please reopen in case.
