### ISSUE TITLE
copyright report confusing fields

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#506]
Tested on #25f4d65 
on mod=copyright-view there are three fields:
  Description
  Text finding
  Comment
What are these for?  Can we have a help mouse over to explain them?

![screen shot 2015-08-26 at 11 59 02 am](https://cloud.githubusercontent.com/assets/8060442/9501680/e4a0fe0a-4be9-11e5-9b12-43b4190fd30c.jpg)

**Comment by mcjaeger** [comment]
we have the "i" buttons already for hoovering over them. 

The are for copyrights not so much relevant, but for ECC and "some other agent in this area. Because th Copyright and the "ECC" share base code, the UI here is the same. brief explanations for the three points:

1. Description: "Classification of the finding, such as 'copyright statement' or 'TSU number' or 'ECC warning' or 'author but no copyright statement' "
2. Text finding: "Exact text finding, if the regular expression match is wrong not matching everything, too much"
3. Comment: "A user can place comment for leaving a notice that ma be viewed by other users on Fossology."

Text finding:
