### ISSUE TITLE
Consider merging some GitHub-labels

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#562]
I would suggest to merge the following [labels](https://github.com/fossology/fossology/labels) (keep the left one):
1.  **`Bug`** <-> `Tracker: Bug`
2. **`in progress`** <-> `Status: In Progress`
3. **`in review`** <-> `Status: Feedback`
4. **`enhancement`** <-> `Tracker: Enhancement`

to be more consistend with waffle.io.

There are also labels, which might be obsolete (i.e. `Status: Resolved`, `Status: New`,...).

**Comment by bufferoverflow** [comment]
:+1:

**Comment by maximilianhuber** [comment]
#### current state of merging
1. added label `Bug` for all Issues with label `Tracker: Bug`.
2. similar to 1. but maybe these labels shoud be removed completly (**to old?**)?
3. added label `needs review` for all Issues with label `Status: Feedback`. I think one should have a look at all 9 of them and decide what label they should have, since this might not be the correct translation.
4. same as 1.

#### next steps:
* look at 2. and 3. (maybe together with @mcjaeger)
* remove old labels

**Comment by mcjaeger** [comment]
@maxhbr tracker label is out, right?

**Comment by mcjaeger** [comment]
Categories are left, but the others solved.
