### ISSUE TITLE
Verify user before creating group

### ISSUE THREAD

**Issue by UShan89** [fossology/fossology#656]
Hello, 

Currently, any user can add/create group 
https://<fossology.url>/?mod=group_add

This action needs to be changed. User with admin rights needs to be able to create a group. Please correct me if I am wrong or if this is a feature not security issue

**Comment by maximilianhuber** [comment]
I am not sure, since new groups not necessarily imply new permissions. I will check that and ask users, whether something speaks against your suggestion.

Not any user is able to create groups. He has to have at least write permissions, i.e. see [group-add.php#L34](https://github.com/fossology/fossology/blob/cfa6128c335b1d347470fc11e5d039b692cf141b/src/www/ui/group-add.php#L34).

**Comment by maximilianhuber** [comment]
see commet at #658:
> A user is also able to manage and delete groups to which he has the correct permissions. This is valid behaviour and does not introduce permission issues.

I will close this issue. Pleas reopen if there are other security concerns which have been overlooked.
