### ISSUE TITLE
ConcludedLicence feature

### ISSUE THREAD

**Issue by jmecosta** [fossology/fossology#694]
hi,

if i understand we can use this feature to automatically create clearing decisions on a particular package? My problem is that for example we are using  boost and fossology detects 100K entries for BSL-1.0 and i would like to auto approve all those entries in the boost folder. is this possiblie?

thanks in advance
jorge costa

**Comment by rlintu** [comment]
There are two options to do that:
- if there are no other licenses in the directory, then you can select in a license browser view from actions [edit], then add BSL-1.0 to selected licenses and choose [Add selected licenses]
- if there are other licenses in the directory besides BSL-1.0, then you should use Bulk recognition. Go to directory, open any BSL-1.0 licensed file, select [Bulk recognition], copy BSL-1.0 license reference to bulk window, add BSL-1.0 license , select [Scan only current folder] and finally select [Schedule bulk scan]

Sounds complicated? It's not after you have done that couple of times.

**Comment by jmecosta** [comment]
:) not complicated after a couple of times indeed. however seems that i have a couple more questions.

1. after running the bulk as suggested i was having the impression that the next time i analyse the same package but with incremented version, the folder in question would reuse what ive cleared in the previous package. but only fle i have cleared using the "Change concluded License" menu was reused. Supose there must be a way to do what i need?

2. we have coded a new rule in nomos, and tried to apply the bulk as decribed above however because the license reference is empty it did not clear they entries i was expecting. i there a way of this this?

thanks again for the help and the prompt reply.

**Comment by rlintu** [comment]
1. The decision scope can be either local or global. Decider agent by default makes decisions in local scope. Bulk scanner calls decider agent thus decisions are local. The same is when you use [Edit] to set license in a directory level. User can set decision scope (local / global) in 'Change concluded License' view by setting 'Clearing decision scope'. The default behaviour (local) is good if several people are doing license analysis. However, if only one or two people with good understanding of licenses are doing license checking, then it might be more efficient to use global scope decisions so that identical files are not needed to check several times. Decision agent default behaviour can be changed by setting ```
define("CLEARING_DECISION_IS_GLOBAL", true);
``` in DeciderJobAgent.php

2. I'm afraid I didn't quite follow you in this question. If you have changed nomos and installed a new version to fossology, then you should rerun nomos for the source code package to see the correct scanner results. But you have to do new decisions for the newly detected licenses.

**Comment by jmecosta** [comment]
Yes make total sence, ive enable the global and now all works as i expected. Ive edit and apply our license, the next analysis reused the results correctly from previous analysis.

One nice observation was that when i edit and add license all files without license showed the added license, 
![image](https://cloud.githubusercontent.com/assets/1041352/18432489/ed6d0bda-78ea-11e6-8c65-f5319d7ac113.png)

But the next upload, only showed the actual number of files with that license :)
![image](https://cloud.githubusercontent.com/assets/1041352/18432503/ff9e90a8-78ea-11e6-972b-4bbe255c257b.png)

Thanks again for the help. i think i can now do a full analysis on our code base.

**Comment by NesrinCeylan** [comment]
Hello ,

on this topic, I have also questions about the usage of the decider after the upload of a folder: 

1. i've uploded a few of folder and wanted to test to conclude after uploading (without setting up some default analize agents). I was wondering if it's possible, after uploading to conclude the specific files, cause there is the option to do that on "jobs" -> "schedule Agents" -> "decider: 1. Automatic concluded licenses decider, based on ...". This options are for just single-files, isn't they?  Is there any options for concluding for whole folder? 

2. How can I handle the "license Admin". I've already gained some insights. But I still wonder how I can add licenses that are not in the db of Fossology and that will be included in the next upload. 

Many Thanks in advance
Nesrin
