### ISSUE TITLE
No option to move uploads from root to a (sub)folder

### ISSUE THREAD

**Issue by silverhook** [fossology/fossology#707]
While it’s possible to move uploads between (sub)folders, I can’t seem to find an option how to move uploads from the root folder to a (sub)folder. I imagine (but may be very wrong) that for newbies, this is a common pitfall.

Use case:
1. upload a few projects
2. work on them
3. create a few folders to bring some order to your chaos
4. scratch your head

Actual result:
- no (apparent) way to do it

Expected result:
- apparent way to do it :smile_cat: 

Possible work-around (has its issues though):
- automatically create a e.g. `Staging` folder and use that instead of root for newbies.

**Comment by mcjaeger** [comment]
?

Organize -> Uploads -> Move upload or folder should work for moving uploads from a root folder to subfolders. Since it is obvious to use the same functionality that works for moving uploads between folders, I might not have understood your issue correctly.
Just tested it for curiosity and seems to work, 1. select level on the left side (in this case no selection necessary), 2. then select upload from the scrollable list field, then 3. select target folder from the pull down menu, in this case a sub folder?

**Comment by silverhook** [comment]
I would assume as much, but:

> 1. select level on the left side (in this case no selection necessary),

Yes, this makes sense.

> 2. then select upload from the scrollable list field, 

Here is where I stumble into the problem – I see no uploads in this list, just (sub)folders.

I tried to select a (sub)folder in step 1. just to see if it’s a bigger issue, but moving from a (sub)folder seems to work fine.

BTW, I am on:
> Version: [unknown], Branch: [master], Commit: [#05fee1] 2016/09/26 11:09 UTC built @ 2016/09/26 11:19 UTC

i.e. the Docker image available at the training at the LinuxCon Europe 2016.

**Comment by max-wittig** [comment]
works in 
Version: [3.1.0rc2], Branch: [master], Commit: [#5e78f5] 2017/03/07 08:54 CET built @ 2017/03/07 14:29 CET
