### ISSUE TITLE
Regression: GPL-2.1[sic] license generates invalid SPDX file

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#748]
This was previously reported in #643 and fixed in PR #633, but appears to be broken again. The steps to reproduce are the same:

Steps to reproduce:
1. Upload from URL https://gist.githubusercontent.com/timurphy/56eb73da5992bf4423af/raw/6273b0b41d25f741a53b2bff52626b1d4f56a698/lgpl_sic.txt with Nomos scan enabled
2. Generate SPDX:RDF file
3. Using the [spdx tools](https://github.com/spdx/tools) project, run the Verify command, which will print this error:

```
This SPDX Document is not valid due to:
	Invalid license id 'LicenseRef-GPL-2.1[sic]'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
```

Tested on Version: [3.1.0rc2], Branch: [master], Commit: [#3b080b]

**Comment by timurphy** [comment]
If a scan is done over the whole https://github.com/fossology/fossology.git project, a number of these cases come up:

```
This SPDX Document is not valid due to:
	Invalid license id 'LicenseRef-Sun(tm)'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-GPL-2.1[sic]'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-GPL-2.0+&GPL-3.0+'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-Public-domain(C)'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-GPL-2.1+[sic]'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-CECILL(dual)'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-MIT&BSD'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id 'LicenseRef-GPL-2.0+:3.0'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
```

**Comment by mcjaeger** [comment]
there was an effort to SPDX-izing all license names in FOSSology, however, the coverage was (presumably) only to licenses in `licenseref.sql`. The result from a scanner seems to lead to other non-SPDX-conformant license IDs.

I am seeing this problem also for ninka (there are non-SPDX-confirming license IDs as well) as well as for:
* user-enetered license candidates (because the user can enter characters beyond letter, numbers, dots and dashes. 
* admin added licenses
* imported licenses
* mind the future SPDX import and license IDs there

What could be done is to have a license ID escaping for using only SPDX conforming characters when generating SPDX files - or just allowing users to enter only those conforming characters 

The definition of using `LicenseRef- ` it is described in https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf
section 3.14.4
