### ISSUE TITLE
Is it OK to run multiple fossology-scheduler containers?

### ISSUE THREAD

**Issue by vnalla** [fossology/fossology#966]
Is it okay to run multiple fossology-scheduler containers that run agents and scheduler which are built using the docker files provided in fossology*/install folder?

**Comment by mcjaeger** [comment]
Hm, I think it is Ok, because there is support for a multi server setup that should be Ok to be run as multiple containers. The architecture supports is to run agents distributed on different computers all getting together to one database server.

But myself, I do not have much expereince with that. You might find some documentation in the section "cluster install" on this page:

http://archive15.fossology.org/projects/fossology/wiki/Debian_Install_2_0

**Comment by maxhbr** [comment]
I think, if you start multiple docker scheduler, they have to share the repository, i.e. the folder `/srv/fossology/repository/` via nfs or docker volumes. 

I am also not sure whether the "cluster install" setup consists of a single scheduler on the "master" which schedules agents on multiple hosts. See for example the configuration in `fossology.conf` as documented on [1]
```
[HOSTS]
localhost = localhost /etc/fossology  10
<agent1_hostname>= <agent1_hostname> /etc/fossology  10
<agent2_hostname>= <agent2_hostname> /etc/fossology  10
```
[1] http://archive15.fossology.org/projects/fossology/wiki/Debian_Install_2_0

**Comment by mcjaeger** [comment]
please reopen if needed to continue discussion on this topic
